-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 20:50:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema me_cafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema me_cafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `me_cafe` DEFAULT CHARACTER SET utf8 ;
USE `me_cafe` ;

-- -----------------------------------------------------
-- Table `me_cafe`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rating` TINYINT(1) NULL,
  `description` VARCHAR(250) NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_brand1_idx` (`brand_id` ASC) ,
  CONSTRAINT `fk_products_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `me_cafe`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`type_grinding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`type_grinding` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`products_type_grinding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`products_type_grinding` (
  `products_id` INT NOT NULL,
  `type_grinding_id` INT NOT NULL,
  INDEX `fk_products_has_type_grinding_type_grinding1_idx` (`type_grinding_id` ASC) ,
  INDEX `fk_products_has_type_grinding_products_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_products_has_type_grinding_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `me_cafe`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_type_grinding_type_grinding1`
    FOREIGN KEY (`type_grinding_id`)
    REFERENCES `me_cafe`.`type_grinding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`products_grames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`products_grames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `products_id` INT NOT NULL,
  `grames` INT NOT NULL,
  `price` DECIMAL(2) NOT NULL,
  INDEX `fk_products_grames_products1_idx` (`products_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_grames_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `me_cafe`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `roles_id` INT NOT NULL,
  `image` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_users_roles1_idx` (`roles_id` ASC) ,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `me_cafe`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_sales_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `me_cafe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`images_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`images_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(250) NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_products_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_images_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `me_cafe`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`detail_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`detail_sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sales_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_has_products_products1_idx` (`products_id` ASC) ,
  INDEX `fk_sales_has_products_sales1_idx` (`sales_id` ASC) ,
  CONSTRAINT `fk_sales_has_products_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `me_cafe`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `me_cafe`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  INDEX `fk_cart_users1_idx` (`users_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cart_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `me_cafe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_cafe`.`detail_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_cafe`.`detail_cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NULL,
  INDEX `fk_cart_has_products_products1_idx` (`products_id` ASC) ,
  INDEX `fk_cart_has_products_cart1_idx` (`cart_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cart_has_products_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `me_cafe`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `me_cafe`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
